input type:keyboard {
    xkb_layout fi
}

input "type:touchpad" {
    dwt enabled           # disable while typing
    dwtp enabled          # disable while trackpoint
    tap enabled
    tap_button_map lrm
    natural_scroll enabled
}
