# Idle and lock configuration
#
# This will lock your screen after 300 seconds of inactivity, then turn off
# your displays after another 60 seconds, and turn your screens back on when
# resumed. After a further 600 seconds the system will suspend. It will also
# lock your screen before your computer goes to sleep.
#
# When the screen is already locked, the displays will turn off after only 60
# seconds of inactivity (and turn back on when resumed).
#
# The timeouts can be customized via the `$lock_timeout`, `$screen_timeout`
# and `$suspend_timeout` variables (defaults: 300, 60 and 600 seconds).
#
# You can also lock the screen manually by running `loginctl lock-session` or
# add a binding for the command. Example:
#     bindsym $mod+Shift+Escape  exec loginctl lock-session
#
# Note that all swaylock customizations are handled via /etc/swaylock/config and
# can be overridden via $XDG_CONFIG_HOME/swaylock/config (~/.config/swaylock/config).
#
# Requires: swayidle
# Requires: swaylock
# Requires: /usr/bin/pkill, /usr/bin/pgrep

exec LT="$lock_timeout" ST="$screen_timeout" SUT="$suspend_timeout" LT=${LT:-300} ST=${ST:-60} SUT=${SUT:-600} && \
    swayidle -w \
        timeout $LT 'swaylock -f' \
        timeout $((LT + ST)) 'swaymsg "output * power off"' \
                      resume 'swaymsg "output * power on"'  \
        timeout $ST 'pgrep -xu "$USER" swaylock >/dev/null && swaymsg "output * power off"' \
             resume 'pgrep -xu "$USER" swaylock >/dev/null && swaymsg "output * power on"'  \
        timeout $((LT + ST + SUT)) 'systemctl suspend' \
        before-sleep 'swaylock -f' \
        lock 'swaylock -f' \
        unlock 'pkill -xu "$USER" -SIGUSR1 swaylock'
