# select workspace
bindsym {
	Control+$mod+left workspace prev
	Control+$mod+right workspace next
}

# Focus to windows
bindsym Mod1+tab focus next

# Rofi
unbindsym $mod+d
bindsym $mod+d exec $rofi_cmd -show drun

bindsym $mod+Shift+d exec $menu
