# select workspace
bindsym {
	Control+$mod+left workspace prev
	Control+$mod+right workspace next
}

# Focus to windows
bindsym {
    Mod1+tab focus next
    $mod+tab exec $rofi_cmd -show window
}

# Rofi
unbindsym {
    $mod+d
    $mod+s 
}
bindsym {
    $mod+d exec $rofi_cmd -show drun
    $mod+Shift+d exec $menu
    $mod+s exec $rofi_cmd -show ssh
}

# Use toolbox as default terminal enviroment
unbindsym $mod+Return
bindsym {
	$mod+Return exec $term --title ToolBox toolbox enter
	$mod+Shift+Return exec $term
}
