# select workspace
bindsym {
	Control+$mod+left workspace prev
	Control+$mod+right workspace next
}

unbindsym {
    $mod+$left focus left
    $mod+$down focus down
    $mod+$up focus up
    $mod+$right focus right
}

# Lock session with Super+l
bindsym $mod+l exec loginctl lock-session

# move window to workspace
bindsym {
	Control+$mod+Shift+left exec ~/.config/sway/scripts/move-ws.sh -1
	Control+$mod+Shift+right exec ~/.config/sway/scripts/move-ws.sh 1
}

# Focus to windows
bindsym {
    Mod1+tab focus next
    $mod+tab exec $rofi_cmd -show window
}

# Rofi
unbindsym {
    $mod+d
    $mod+s 
}
bindsym {
    $mod+d exec $rofi_cmd -show drun
    $mod+Shift+d exec $menu
    $mod+s exec $rofi_cmd -show ssh
    Mod1+space exec $rofi_cmd -show drun
}

# Use toolbox as default terminal enviroment
unbindsym $mod+Return
bindsym {
	$mod+Return exec $term --title ToolBox toolbox enter
	$mod+Shift+Return exec $term
}

# Lid actions
bindswitch lid:off exec kanshictl reload

# Sway notication center
bindsym $mod+n exec swaync-client -t
